### PR TITLE
Use system default for timezone

### LINKED ISSUE #1240: Wrong timestamp pictures. Off by 2 hours
### Describe the bug

When auto uploading pictures the picture has the wrong timestamp in memories. (Its 2 hours off)

The server timezone is correct as is also the nextcloud timezone.

### Steps To Reproduce

Always

### Platform

```markdown
- OS:debian 12
- Browser: native android app
- Memories Version:latest
- Nextcloud Version:latest
- PHP Version:8.2
```

### Screenshots

_No response_

### Additional context

- Any errors in the JS console?
- Any errors in the Nextcloud server logs?

### PR DESCRIPTION
**Pull request by yamanq**
The TZ environment variable is not set on many machines and date_default_timezone_get only works if the timezone has been set elsewhere. Instead, this approach relies on the Nextcloud server configuration for the timezone.

Closes #1240

See: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#default-timezone

### CODE REVIEW

File: lib/Db/TimelineWrite.php [hunk 1]
```diff
@@ -121,7 +123,7 @@ public function processFile(
         [$lat, $lon, $mapCluster] = $this->processExifLocation($fileId, $exif, $prevRow);
 
         // Get date parameters (after setting timezone offset)
-        $dateTaken = Exif::getDateTaken($file, $exif);
+        $dateTaken = Exif::getDateTaken($file, $exif, $this->config->getSystemValue('default_timezone', 'UTC'));
```
Comment (pulsejet) [inline lib/Db/TimelineWrite.php:126]: This will always override the `getenv` fallback

File: lib/Exif.php [hunk 2]
```diff
@@ -248,7 +248,7 @@ public static function getDateTaken(File $file, array $exif): \DateTime
         $dt = new \DateTime('@'.$file->getMtime());
 
         // Set timezone to system timezone
-        $tz = getenv('TZ') ?: date_default_timezone_get();
+        $tz = $timezone ?: getenv('TZ') ?: date_default_timezone_get();
```
Comment (pulsejet) [inline lib/Exif.php:251]: Preferable to use `OCA\Memories\Settings\SystemConfig`

**Review by pulsejet — APPROVED** [review]
Thanks, I'll take care of the above comments before merge
