### PR TITLE
fix: Fix a bug that caused some unassigned face photos to be unselectable

### LINKED ISSUE #721: unassigned face > selection problem
**Describe the bug**
I have a selection problem when I start to have selections, some photos are no longer selectable. 

Also, when I assign a group of photos (e.g. 10), sometimes some photos are not assigned.)

**To Reproduce**

**Screenshots**

https://github.com/pulsejet/memories/assets/45015615/8c572d86-bda4-4e6b-94a1-d0442a0ba3ce

https://discord.com/channels/1100157156742926406/1100158171621904567/1125686985063944193

**Platform:**

- OS: OMV 6
- Browser: Firefox
- Memories Version: 5.2.1
- Nextcloud Version: 27.0.0
- PHP Version: 8.2.7

**Additional context**

- Any errors in the JS console?  No
- Any errors in the Nextcloud server logs? No

### PR DESCRIPTION
**Pull request by g3n35i5**
This resolves #721

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -228,7 +283,7 @@ export type ISelectionAction = {
   /** Icon component */
   icon: any;
   /** Action to perform */
-  callback: (selection: Map<number, IPhoto>) => Promise<void>;
+  callback: (selection: any) => Promise<void>;
```
Comment (g3n35i5) [inline src/types.ts:286]: The type should be `SelectionProxy` but this doesn't work. Can someone help out here?

File: src/components/SelectionManager.vue [hunk 2]
```diff
@@ -246,8 +244,17 @@ export default defineComponent({
...
+    deleteSelectedPhotosById(delIds: number[], selection: SelectionProxy) {
+      let photosToDelete: IPhoto[] = []
+      for (const photo of selection.values()) {
+        if (photo === undefined) {
+          continue
+        }
+        if (delIds.indexOf(photo.fileid) > -1) {
+          photosToDelete.push(photo)
+        }
+      }
```
Comment (pulsejet) [inline src/components/SelectionManager.vue:256]: 1. Why not just `selection.values().filter( ... )`?
2. Can get a safer time complexity by making `delIds` a `Set` first

File: src/components/SelectionManager.vue [hunk 3]
```diff
@@ -563,19 +570,19 @@ export default defineComponent({
...
         this.selectionChanged();
       } else {
         photo.flag &= ~this.c.FLAG_SELECTED;
 
         // Only do this if the photo in the selection set is this one.
         // The problem arises when there are duplicates (e.g. face rect)
         // in the list, which creates an inconsistent state if we do this.
-        if (this.selection.get(photo.fileid) === photo) {
-          this.selection.delete(photo.fileid);
+        if (this.selection.get(photo) === photo) {
```
Comment (pulsejet) [inline src/components/SelectionManager.vue:584]: This comment and check should no longer be relevant.

File: src/types.ts [hunk 4]
```diff
@@ -220,6 +220,61 @@ export type ITick = {
   key?: number;
 };
 
+export class SelectionProxy {
```
Comment (pulsejet) [inline src/types.ts:223]: `types.ts` is intended only for interfaces, not implementations (this way, you can `import type ...`). This class can move to another file.

File: src/types.ts [hunk 5]
```diff
@@ -220,6 +220,61 @@ export type ITick = {
...
+  private map: Map<string, IPhoto> = new Map<string, IPhoto>();
+
+  add(photo: IPhoto): this {
+    this.map.set(photo.key!, photo);
+    return this;
+  }
+
+  get(photo: IPhoto): IPhoto | undefined {
+    return this.map.get(photo.key!);
```
Comment (pulsejet) [inline src/types.ts:232]: This, precisely, could be the issue. `Photo.key` is nullable because, well, it can be null. The bang operator discards this information without a check. There are indeed a bunch of places where we "fake" a `IPhoto` object that doesn't have a key.

By now though, I'm hoping the selection manager doesn't have to deal with these things. So a runtime assertion here _might_ suffice, so we know if something breaks.

**Review by pulsejet — COMMENTED** [review]
Thanks for this @g3n35i5. I'll go ahead and merge this in with a few updates today.

BTW #773 is related to aggravating this issue; that patch might help.
